plugins {
    id 'fabric-loom' version '1.14.1'
    id 'maven-publish'
}

version = project.properties['mod_version'] ?: '2.0 Stable'
group = project.properties['maven_group'] ?: 'sl.selene'
base {
    archivesName = project.properties['archives_base_name'] ?: 'selene'
}

loom {
    accessWidenerPath = file("src/main/resources/selene.accesswidener")
    mixin {
        useLegacyMixinAp = true
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://maven.fabricmc.net/" }
    maven { url "https://libraries.minecraft.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    compileOnly "org.projectlombok:lombok:1.18.34"
    annotationProcessor "org.projectlombok:lombok:1.18.34"
}

processResources {
    inputs.property "version", project.version
    
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = 'UTF-8'
    it.options.compilerArgs.addAll(['-Xmaxerrs', '10000'])
}

java {
    withSourcesJar()
    
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.named('sourcesJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}